general:
  repository:
    url: 'git@gitlab.internal.sanger.ac.uk:sanger-pathogens/general.git'
    branch: 'master'
  directories_to_build: ['c','config','data','java','lua','perl','python','r','shell']

checkout_directory: "/tmp"

directories:
  production_bin:    '/software/pathogen/internal/prod/bin'
  production_lib:    '/software/pathogen/internal/prod/lib'
  pathdev_bin:       '/software/pathogen/internal/pathdev/bin' 
  pathdev_config:    '/software/pathogen/config' 
  production_java:   '/software/pathogen/internal/pathdev/java'
  production_etc:    '/software/pathogen/etc'
  documentation:     '/nfs/WWWdev/INTWEB_docs/htdocs/Teams/Team81/docs'

application_locations:
  perl:           '/software/bin/perl'
  natural_docs:   '/software/pathogen/external/apps/usr/local/NaturalDocs-1.52/NaturalDocs'
  source_control: '/usr/bin/git'
  make:           '/usr/bin/make'
deployment:
  server: 'pathpipe-farm3'
  user: 'pathdb'
  checksums: '/software/pathogen/internal/prod/deployment_checksums.log'
